- name: Ensure Java is installed.
  package:
    name: "{{ java_packages }}"
    state: present


- name: copy build file from local to remote server
  copy:
    src: /Docker-Project/target/spring-petclinic-2.7.0-SNAPSHOT.jar
    dest: /spring-petclinic.jar

- name: running the build file
  become: True
  shell: java -jar /spring-petclinic.jar
  async: 20
  poll: 0
